#Expyriment 1.0.0 (Python 3.13.7), .xpe-file, coding: cp1251
#date: Sun Oct 12 2025 16:54:10
#sha1: 0f0bd6
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Windows', node='LAPTOP-AFL7R53R', release='10', version='10.0.19045', machine='AMD64')
Time,Type,Event,Value,Detail,Detail2
276,stderr,received,'Traceback (most recent call last):'
277,stderr,received,'  File "d:\\Аня\\2025-2026\\cogsup\\Programming\\Assignments\\Week-5\\Exercises\\blindspot2.py", line 102, in <module>\n    control.start(subject_id=subject_id, data_folder="data")\n    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'
277,stderr,received,"TypeError: start() got an unexpected keyword argument 'data_folder'"
